config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
end

app/models/contact.rb
class Contact <MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true
  
  def headers
    {
    :subject => "Contact Form",
    :to => "michellecolon.mc@gmail.com",
    :from => %("#{name}" <#{email}>)
    }    
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
xclass PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]

def index
  @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
end

def new
  @post = Post.new
end

def create
  @post = Post.new post_params

  if @post.save
    redirect_to @post, notice: "Your post was successfully saved!"
  else
    render 'new', notice: "Oh no, your post didn't save :("
  end   
end

def show
end

def edit
end

def update
  if @post.update post_params
    redirect_to @post, notice: "Your post was successfully saved!"
  else
    render 'edit'
  end  
end

def destroy
  @post.destroy
  redirect_to posts_path
end

private

def post_params
  params.require(:post).permit(:title, :content, :slug)
end

def find_post
  @post = Post.friendly.find(params[:id])
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 before_action :find_project, only: [:show, :edit, :update, :destroy]
 def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end 

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "You successfully saved that blog post!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "You just successfully updated your blog post!"
    else
      render 'edit'
    end  
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :content, :slug)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h6 id="page_title">Say Hello!</h6>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you soon :)</p>
</div>

app/views/contacts/new.html.erb
<h6 id="page_title">Say Hello!</h6>

  <div class="skinny_wrapper wrapper_padding">
    <%= form_for @contact do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true %>

      <br>
      
      <%= f.label :email %><br>
      <%= f.email_field :email, required: true %>

      <br>

      <%= f.label :message %><br>
      <%= f.text_area :message, as: :text %>

      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <%= f.submit 'Hello!', class: "button" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Michelle Col&oacute;n- Web Developer</title>
 <link href='https://fonts.googleapis.com/css?family=Raleway:400,700,400italic' rel='stylesheet' type='text/css'>
 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="scss/application.scss">

  <link rel="stylesheet" href="scss/welcome.css">


  <link rel="stylsheet" href="normalize.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="main_navigation" class="clearfix">
    <%= link_to "Michelle Colón", root_path, class: "name" %>
    <nav>
      <%= link_to "Portfolio", posts_path %>
      <%= link_to "Blog", projects_path %>
      <a href="contact.html">Contact</a>
    </nav>
  </header>

<%= yield %>

  <footer id="main_footer">
    <p class="copyright">&copy; 2016 Michelle Col&oacute;n </p>
    <nav>
      <a href="https://github.com/michellecolon" target="_blank"><i class="fa fa-github"></i></a>
      <a href="https://www.linkedin.com/in/michellecolon"  target="_blank"><i class="fa fa-linkedin"></i></a>
      <a href="https://twitter.com/michellewebdev"  target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.instagram.com/michellewebdev/"  target="_blank"><i class="fa fa-instagram"></i></a>
    </nav>
  </footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
var disqus_shortname = 'mcwd';
var disqus_identifier = '<%= @post.id %>';
var disqus_title = '<%= @post.title %>';
var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//mcwd.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %>prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "Write your article here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h6 id="page_title">Portfolio</h6>

<div id="posts_wrapper" class="skinny_wrapper">
  <%= @posts.each do |post| %>
    <div class="post">
      <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
      <h2><a href="#"><%= link_to post.title, post %></a></h2>
      <hr>
    </div>
  <% end %>
</div>
  
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <h6><%= @post.title %></h6>
    <hr>
  </header>

  <div id="content">
   <%= @post.content %>
  </div>

  <hr>

  <div id="share_box">
    <!-- Twitter -->
    <p>Share Insert Project Thumbnail 1 Here</p>
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @michellewebdev - &amp;url=<%=url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=800, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=800, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=800, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
  </div>

  <hr>

  <%= render 'disqus' %>

  </div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <h2><%= pluralize(@project.errors.count, "error") %>prevented this project from saving</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "Write your blog post here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper warpper_padding">
  <h1>Edit Blog Post</h1>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h6 id="page_title">Blog</h6>

<div id="posts_wrapper" class="skinny_wrapper">
  <%= @projects.each do |project| %>
    <div class="post">
      <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
      <h2><a href="#"><%= link_to project.title, project %></a></h2>
      <hr>
    </div>
  <% end %>
</div>
  

app/views/projects/new.html.erb
<div class="skinny_wrapper warpper_padding">
  <h1>New Blog Post</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
    <h6><%= @project.title %></h6>
    <hr>
  </header>

  <div id="content">
   <%= @project.content %>
  </div>

  <%= link_to "Edit", edit_project_path(@project) %>
  <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this blog post?!"} %>

  <hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class=".col-1 about homepage_content">
    <h2>About</h2>
    <hr>
    <p>first paragraph about myself</p>
    <p>second paragraph about myself</p>
  </div>

  <div class=".col-2 homepage_content">
    <h2>My Most Recent Creations</h2>
    <hr>
    <% @projects.each do |project| %>
      <h3><a href="#"><%= link_to project.title, project %></a></h3>
      <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>

  <div class=".col-3 homepage_content">
    <h2>Blog</h2>
    <hr>
    <% @posts.each do |post| %>
      <h3><a href="#"><%= link_to post.title, post %></a></h3>
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>
</div>